name: Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * 0' # Runs every Sunday at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  static-code-analysis:
    name: Static Code Security Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Bandit and Flake8
        run: |
          python -m pip install --upgrade pip
          pip install bandit flake8

      - name: Run Bandit Security Scan
        run: bandit -r keyspy

      - name: Run Flake8 for Linting
        run: flake8 .

  dependency-vulnerability-scan:
    name: Dependency Vulnerability Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Safety
        run: |
          python -m pip install --upgrade pip
          pip install safety

      - name: Run Safety Scan
        run: safety check --full-report

  secrets-detection:
    name: Secrets Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run GitHub Secrets Scanner
        uses: actions/secret-scanning@v1

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install trufflehog

      - name: Scan Repository with TruffleHog
        run: trufflehog filesystem --directory . --json

  container-security-scan:
    name: Container Vulnerability Scanning
    runs-on: ubuntu-latest
    if: github.repository == 'keyspy/keyspy-docker'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t keyspy/keyspy:latest .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          image-ref: keyspy/keyspy:latest

  sbom-generation:
    name: Generate SBOM (Software Bill of Materials)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install CycloneDX
        run: |
          python -m pip install --upgrade pip
          pip install cyclonedx-bom

      - name: Generate SBOM
        run: cyclonedx-py -o bom.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: SBOM
          path: bom.json

  audit-logs:
    name: Security Audit Logs
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Security Audit Logs
        uses: actions/github-script@v7
        with:
          script: |
            const logs = await github.securityAdvisories.listForOrg({
              org: context.repo.owner,
            });
            console.log(logs);
